<?php

declare(strict_types=1);

namespace App\Services;

use App\Audit\AuditService;
use App\Auth\PermissionService;
use App\Cms\CmsFormatter;
use App\Cms\LineDiff;
use App\Cms\ReservedPaths;
use App\Cms\SeoAnalyzer;
use App\Exceptions\AuthorizationException;
use App\Exceptions\DomainRuleException;
use App\Exceptions\ValidationException;
use App\Models\User;
use App\Notifications\NotificationService;
use App\Repositories\CmsPageRepository;
use App\Support\Application;
use App\Support\Db;
use App\Support\Slug;
use App\Support\Ulid;

/**
 * Website pages: writing, reviewing, publishing, scheduling, versioning and trashing them.
 *
 * Who may do what (permissions `cms.*`):
 *  - `cms.manage`  — write pages, save drafts, submit for review, duplicate, trash, restore a revision. Editing a page that is
 *    already published (or scheduled) needs `cms.publish` too, so live content can never change without a publisher.
 *  - `cms.publish` — publish now or at a chosen time, set a take-down time, unpublish, archive, send back from review,
 *    empty the trash for good.
 * Workflow: draft → review → published ⇄ draft → archived → draft; any page can go to the trash and come back.
 * Rules: the address (path) is unique, made of one to three lowercase segments, cannot start with something a route already
 * uses, and is frozen once the page has been published; every content save writes a revision (the newest 50 are kept) and
 * bumps `version`, which doubles as the edit-conflict check; a page is public only inside its [go-live, take-down) window.
 * What the editor typed is kept as `body_source`; the HTML is generated by CmsFormatter on every save.
 */
final class CmsPageService
{
    public const MAX_REVISIONS = 50;
    public const PREVIEW_DAYS = 7;
    public const MAX_PREVIEW_LINKS = 5;
    public const MAX_FAQ = 20;
    public const BULK_LIMIT = 100;

    public const TEMPLATES = ['default' => 'Standard (readable column)', 'wide' => 'Wide (full width)', 'landing' => 'Landing (no menu or footer)'];
    public const CHANGEFREQ = ['daily', 'weekly', 'monthly', 'yearly'];

    /** Columns an editor can change; the revision snapshot stores the ones after title/body. */
    private const SNAPSHOT = [
        'path', 'summary', 'template', 'meta_title', 'meta_description', 'focus_keyword', 'canonical_url', 'robots', 'og_title', 'og_description',
        'featured_image', 'featured_alt', 'in_sitemap', 'sitemap_priority', 'sitemap_changefreq', 'faq',
    ];

    public function __construct(
        private readonly CmsPageRepository $pages,
        private readonly PermissionService $permissions,
        private readonly AuditService $audit,
        private readonly Db $db,
        private readonly ReservedPaths $reserved,
        private readonly NotificationService $notifications,
        private readonly Application $app,
    ) {
    }

    // ---- writing --------------------------------------------------------------------------------------------

    /**
     * @param array<string,mixed> $input
     * @return string the new page's public id
     * @throws AuthorizationException|ValidationException
     */
    public function create(array $input, User $actor): string
    {
        $this->assertManage($actor);
        $data = $this->validated($input, null, $actor);
        $publicId = Ulid::generate();

        $this->db->transaction(function () use ($data, $publicId, $actor): void {
            $id = $this->pages->create($this->row($data) + [
                'public_id' => $publicId, 'status' => 'draft', 'version' => 1, 'author_id' => $actor->id, 'updated_by' => $actor->id,
                'publish_at' => $data['publish_at'], 'unpublish_at' => $data['unpublish_at'],
            ]);
            $this->pages->addRevision($id, 1, $data['title'], $data['body_source'], $this->snapshot($data), 'Created', $actor->id);
            $this->audit->log('cms_page_created', 'cms', 'cms_page', $id, null, ['title' => $data['title'], 'path' => $data['path']], null, $actor);
        });

        return $publicId;
    }

    /**
     * @param array<string,mixed> $input includes `version` (the version the editor loaded, for the conflict check)
     * @return list<string> the fields that changed (empty = nothing to save)
     * @throws AuthorizationException|DomainRuleException|ValidationException
     */
    public function update(string $publicId, array $input, User $actor): array
    {
        $this->assertManage($actor);
        $page = $this->load($publicId);
        $this->assertEditable($page, $actor);
        if ((int) ($input['version'] ?? 0) !== (int) $page['version']) {
            throw new DomainRuleException('EDIT_CONFLICT', 'Someone else saved this page while you were editing (now version ' . (int) $page['version'] . '). Your changes were not saved — copy them, reload the page and apply them again.', [], 409);
        }
        $data = $this->validated($input, $page, $actor);

        $changed = [];
        foreach (['title', 'body_source', ...self::SNAPSHOT] as $col) {
            if ((string) ($data[$col] ?? '') !== (string) ($page[$col] ?? '')) {
                $changed[] = $col;
            }
        }
        foreach (['publish_at', 'unpublish_at'] as $col) {
            if ($this->mayPublish($actor) && (string) ($data[$col] ?? '') !== (string) ($page[$col] ?? '')) {
                $changed[] = $col;
            }
        }
        if ($changed === []) {
            return [];
        }

        $this->db->transaction(function () use ($page, $data, $actor, $changed): void {
            $version = (int) $page['version'] + 1;
            $update = $this->row($data) + ['version' => $version, 'updated_by' => $actor->id];
            if ($this->mayPublish($actor)) {
                $update['publish_at'] = $data['publish_at'];
                $update['unpublish_at'] = $data['unpublish_at'];
            }
            $this->pages->update((int) $page['id'], $update);
            $this->pages->addRevision((int) $page['id'], $version, $data['title'], $data['body_source'], $this->snapshot($data), null, $actor->id);
            $this->pages->pruneRevisions((int) $page['id'], self::MAX_REVISIONS);
            $this->audit->log('cms_page_updated', 'cms', 'cms_page', (int) $page['id'], ['fields' => 'v' . $page['version']], ['fields' => implode(', ', $changed), 'version' => $version], null, $actor);
        });

        return $changed;
    }

    /**
     * A copy as a new draft: "Copy of …" at a free address, same content and SEO settings, none of the dates.
     *
     * @throws AuthorizationException|DomainRuleException
     */
    public function duplicate(string $publicId, User $actor): string
    {
        $this->assertManage($actor);
        $page = $this->load($publicId);
        $newId = Ulid::generate();
        $path = $this->freePath((string) $page['path'] . '-copy');
        $title = mb_substr('Copy of ' . (string) $page['title'], 0, 180);

        $this->db->transaction(function () use ($page, $newId, $path, $title, $actor): void {
            $row = [];
            foreach (['summary', 'body_source', 'body_html', 'template', 'meta_title', 'meta_description', 'focus_keyword', 'canonical_url', 'robots', 'og_title', 'og_description', 'featured_image', 'featured_alt', 'in_sitemap', 'sitemap_priority', 'sitemap_changefreq', 'faq', 'word_count'] as $c) {
                $row[$c] = $page[$c];
            }
            $id = $this->pages->create($row + ['public_id' => $newId, 'path' => $path, 'title' => $title, 'status' => 'draft', 'version' => 1, 'author_id' => $actor->id, 'updated_by' => $actor->id]);
            $copy = $this->pages->find($newId) ?? [];
            $this->pages->addRevision($id, 1, $title, (string) $page['body_source'], $this->snapshotFromRow($copy), 'Duplicated from ' . $page['path'], $actor->id);
            $this->audit->log('cms_page_duplicated', 'cms', 'cms_page', $id, null, ['from' => $page['path'], 'path' => $path], null, $actor);
        });

        return $newId;
    }

    // ---- workflow -------------------------------------------------------------------------------------------

    /** draft → review; publishers are notified. @throws AuthorizationException|DomainRuleException */
    public function submitForReview(string $publicId, User $actor): void
    {
        $this->assertManage($actor);
        $page = $this->load($publicId);
        $this->move($page, ['draft'], 'review', 'cms_page_submitted', $actor, 'Only a draft can be submitted for review.');
        $this->notifyPublishers($page, $actor);
    }

    /** review → draft. @throws AuthorizationException|DomainRuleException */
    public function sendBack(string $publicId, User $actor): void
    {
        $this->assertPublish($actor);
        $this->move($this->load($publicId), ['review'], 'draft', 'cms_page_sent_back', $actor, 'Only a page under review can be sent back.');
    }

    /**
     * Publish now, or at `$goLiveAt` (a local date-time in the business time zone, `Y-m-d\TH:i`).
     *
     * @throws AuthorizationException|DomainRuleException|ValidationException
     */
    public function publish(string $publicId, User $actor, ?string $goLiveAt = null): void
    {
        $this->assertPublish($actor);
        $page = $this->load($publicId);
        if (!in_array($page['status'], ['draft', 'review', 'archived'], true)) {
            throw new DomainRuleException(DomainRuleException::INVALID_TRANSITION, 'Only a draft, a page under review or an archived page can be published.', [], 422);
        }
        $goLive = null;
        $goLiveAt = $goLiveAt === null ? '' : trim($goLiveAt);
        if ($goLiveAt !== '') {
            $goLive = $this->parseLocal($goLiveAt);
            if ($goLive === null) {
                throw new ValidationException(['publish_at' => ['Enter the go-live time as a date and time.']]);
            }
            if (strtotime($goLive . ' UTC') < time() - 60) {
                throw new ValidationException(['publish_at' => ['The go-live time is in the past — leave it empty to publish now.']]);
            }
        }
        $start = $goLive ?? gmdate('Y-m-d H:i:s');
        if ($page['unpublish_at'] !== null && strtotime((string) $page['unpublish_at'] . ' UTC') <= strtotime($start . ' UTC')) {
            throw new ValidationException(['unpublish_at' => ['The take-down time is not after the go-live time — change it first.']]);
        }

        $changes = ['status' => 'published', 'publish_at' => $goLive, 'updated_by' => $actor->id];
        if ($page['published_at'] === null) {
            $changes['published_at'] = $start;
        }
        $this->db->transaction(function () use ($page, $changes, $actor, $goLive): void {
            $this->pages->update((int) $page['id'], $changes);
            $this->audit->log($goLive === null ? 'cms_page_published' : 'cms_page_scheduled', 'cms', 'cms_page', (int) $page['id'], ['status' => $page['status']], ['status' => 'published', 'go_live' => $goLive, 'path' => $page['path']], null, $actor);
        });
    }

    /** published → draft. @throws AuthorizationException|DomainRuleException */
    public function unpublish(string $publicId, User $actor): void
    {
        $this->assertPublish($actor);
        $this->move($this->load($publicId), ['published'], 'draft', 'cms_page_unpublished', $actor, 'Only a published page can be unpublished.');
    }

    /** draft/review/published → archived. @throws AuthorizationException|DomainRuleException */
    public function archive(string $publicId, User $actor): void
    {
        $this->assertPublish($actor);
        $this->move($this->load($publicId), ['draft', 'review', 'published'], 'archived', 'cms_page_archived', $actor, 'This page cannot be archived from its current state.');
    }

    /** archived → draft. @throws AuthorizationException|DomainRuleException */
    public function restoreArchived(string $publicId, User $actor): void
    {
        $this->assertManage($actor);
        $this->move($this->load($publicId), ['archived'], 'draft', 'cms_page_restored', $actor, 'Only an archived page can be restored to a draft.');
    }

    /** @throws AuthorizationException|DomainRuleException */
    public function trash(string $publicId, User $actor): void
    {
        $this->assertManage($actor);
        $page = $this->load($publicId);
        if ($page['deleted_at'] !== null) {
            throw new DomainRuleException(DomainRuleException::INVALID_TRANSITION, 'That page is already in the trash.', [], 422);
        }
        if ($page['status'] === 'published') {
            $this->assertPublish($actor);   // taking a live page off the site is a publisher's decision
        }
        $this->pages->update((int) $page['id'], ['deleted_at' => gmdate('Y-m-d H:i:s'), 'updated_by' => $actor->id]);
        $this->audit->log('cms_page_trashed', 'cms', 'cms_page', (int) $page['id'], null, ['path' => $page['path']], null, $actor);
    }

    /** @throws AuthorizationException|DomainRuleException */
    public function restoreFromTrash(string $publicId, User $actor): void
    {
        $this->assertManage($actor);
        $page = $this->load($publicId);
        if ($page['deleted_at'] === null) {
            throw new DomainRuleException(DomainRuleException::INVALID_TRANSITION, 'That page is not in the trash.', [], 422);
        }
        if ($page['status'] === 'published') {
            $this->assertPublish($actor);   // it would go straight back onto the site
        }
        $this->pages->update((int) $page['id'], ['deleted_at' => null, 'updated_by' => $actor->id]);
        $this->audit->log('cms_page_untrashed', 'cms', 'cms_page', (int) $page['id'], null, ['path' => $page['path']], null, $actor);
    }

    /** Delete a trashed page and its history for good. @throws AuthorizationException|DomainRuleException */
    public function purge(string $publicId, User $actor): void
    {
        $this->assertPublish($actor);
        $page = $this->load($publicId);
        if ($page['deleted_at'] === null) {
            throw new DomainRuleException(DomainRuleException::INVALID_TRANSITION, 'Only a page in the trash can be deleted for good.', [], 422);
        }
        $this->db->transaction(function () use ($page, $actor): void {
            $this->pages->delete((int) $page['id']);
            $this->audit->log('cms_page_purged', 'cms', 'cms_page', (int) $page['id'], ['path' => $page['path'], 'title' => $page['title']], null, null, $actor);
        });
    }

    /**
     * One action over many pages. Each page is judged on its own — a page that cannot take the action is skipped with a reason.
     *
     * @param list<string> $publicIds
     * @return array{done:int,skipped:list<string>}
     * @throws ValidationException
     */
    public function bulk(string $action, array $publicIds, User $actor): array
    {
        $map = [
            'publish' => fn (string $id) => $this->publish($id, $actor),
            'unpublish' => fn (string $id) => $this->unpublish($id, $actor),
            'archive' => fn (string $id) => $this->archive($id, $actor),
            'review' => fn (string $id) => $this->submitForReview($id, $actor),
            'trash' => fn (string $id) => $this->trash($id, $actor),
            'untrash' => fn (string $id) => $this->restoreFromTrash($id, $actor),
        ];
        if (!isset($map[$action])) {
            throw new ValidationException(['action' => ['Choose an action.']]);
        }
        $ids = array_values(array_unique(array_filter($publicIds, static fn ($v): bool => is_string($v) && preg_match('/^[0-9A-Z]{26}$/D', $v) === 1)));
        if ($ids === []) {
            throw new ValidationException(['ids' => ['Tick at least one page.']]);
        }
        if (count($ids) > self::BULK_LIMIT) {
            throw new ValidationException(['ids' => ['At most ' . self::BULK_LIMIT . ' pages at a time.']]);
        }
        $done = 0;
        $skipped = [];
        foreach ($ids as $id) {
            $page = $this->pages->find($id);
            $label = $page === null ? $id : (string) $page['title'];
            try {
                $map[$action]($id);
                $done++;
            } catch (DomainRuleException|AuthorizationException|ValidationException $e) {
                $skipped[] = $label . ': ' . ($e instanceof ValidationException ? (string) (array_values($e->errors())[0][0] ?? 'not valid') : $e->getMessage());
            }
        }

        return ['done' => $done, 'skipped' => $skipped];
    }

    // ---- revisions ------------------------------------------------------------------------------------------

    /** Put an earlier version's content back as a new version. @throws AuthorizationException|DomainRuleException */
    public function restoreRevision(string $publicId, int $version, User $actor): void
    {
        $this->assertManage($actor);
        $page = $this->load($publicId);
        $this->assertEditable($page, $actor);
        $rev = $this->pages->revision((int) $page['id'], $version) ?? throw new DomainRuleException(DomainRuleException::RULE_VIOLATION, 'That version does not exist (old versions are pruned after 50 saves).', [], 404);
        $snap = json_decode((string) $rev['snapshot'], true);
        $snap = is_array($snap) ? $snap : [];
        $snap['path'] = $page['path'];   // an address never travels back in time

        $data = ['title' => (string) $rev['title'], 'body_source' => (string) $rev['body_source']];
        foreach (self::SNAPSHOT as $c) {
            $data[$c] = $snap[$c] ?? $page[$c];
        }
        $html = CmsFormatter::toHtml($data['body_source']);
        $newVersion = (int) $page['version'] + 1;
        $this->db->transaction(function () use ($page, $data, $html, $newVersion, $version, $actor): void {
            $update = ['title' => $data['title'], 'body_source' => $data['body_source'], 'body_html' => $html, 'word_count' => CmsFormatter::wordCount($html), 'version' => $newVersion, 'updated_by' => $actor->id];
            foreach (self::SNAPSHOT as $c) {
                if ($c !== 'path') {
                    $update[$c] = $data[$c];
                }
            }
            $this->pages->update((int) $page['id'], $update);
            $this->pages->addRevision((int) $page['id'], $newVersion, $data['title'], $data['body_source'], $this->snapshot($data), "Restored from version {$version}", $actor->id);
            $this->pages->pruneRevisions((int) $page['id'], self::MAX_REVISIONS);
            $this->audit->log('cms_page_reverted', 'cms', 'cms_page', (int) $page['id'], ['version' => $page['version']], ['restored_from' => $version, 'version' => $newVersion], null, $actor);
        });
    }

    /** @return list<array{op:string,text:string}> the body of version $a compared with version $b (0 = the current page) */
    public function compare(string $publicId, int $a, int $b): array
    {
        $page = $this->load($publicId);
        $text = function (int $v) use ($page): string {
            if ($v === 0 || $v === (int) $page['version']) {
                return (string) $page['body_source'];
            }
            $rev = $this->pages->revision((int) $page['id'], $v) ?? throw new DomainRuleException(DomainRuleException::RULE_VIOLATION, "Version {$v} does not exist.", [], 404);

            return (string) $rev['body_source'];
        };

        return LineDiff::compare($text($a), $text($b));
    }

    // ---- preview links --------------------------------------------------------------------------------------

    /**
     * A link that shows the page, whatever its status, to anyone who has it — for a week. Only the hash of the token is stored.
     *
     * @return string the token (shown once)
     * @throws AuthorizationException|DomainRuleException
     */
    public function createPreviewLink(string $publicId, User $actor): string
    {
        $this->assertManage($actor);
        $page = $this->load($publicId);
        if ($this->pages->activePreviewTokens((int) $page['id']) >= self::MAX_PREVIEW_LINKS) {
            throw new DomainRuleException(DomainRuleException::RULE_VIOLATION, 'This page already has ' . self::MAX_PREVIEW_LINKS . ' active preview links. Revoke them first.', [], 422);
        }
        $token = bin2hex(random_bytes(24));
        $this->pages->addPreviewToken((int) $page['id'], hash('sha256', $token), gmdate('Y-m-d H:i:s', time() + self::PREVIEW_DAYS * 86400), $actor->id);
        $this->audit->log('cms_preview_link_created', 'cms', 'cms_page', (int) $page['id'], null, ['days' => self::PREVIEW_DAYS], null, $actor);

        return $token;
    }

    /** @throws AuthorizationException|DomainRuleException */
    public function revokePreviewLinks(string $publicId, User $actor): int
    {
        $this->assertManage($actor);
        $page = $this->load($publicId);
        $n = $this->pages->revokePreviewTokens((int) $page['id']);
        if ($n > 0) {
            $this->audit->log('cms_preview_links_revoked', 'cms', 'cms_page', (int) $page['id'], null, ['count' => $n], null, $actor);
        }

        return $n;
    }

    /** The page a preview token opens (null for anything that is not a live, unexpired token). @return array<string,mixed>|null */
    public function pageForPreview(string $token): ?array
    {
        return preg_match('/^[a-f0-9]{48}$/D', $token) === 1 ? $this->pages->pageForPreviewToken(hash('sha256', $token)) : null;
    }

    // ---- SEO ------------------------------------------------------------------------------------------------

    /** @param array<string,mixed> $page @return array{score:int,checks:list<array{level:string,text:string}>} */
    public function seo(array $page): array
    {
        $title = trim((string) (($page['meta_title'] ?? '') !== '' ? $page['meta_title'] : ($page['title'] ?? '')));

        return SeoAnalyzer::analyze($page, $title === '' ? 0 : $this->pages->titleCount($title, (int) ($page['id'] ?? 0)));
    }

    // ---- rules ------------------------------------------------------------------------------------------------

    public function mayManage(User $u): bool
    {
        return $this->permissions->userCan($u, 'cms.manage');
    }

    public function mayPublish(User $u): bool
    {
        return $this->permissions->userCan($u, 'cms.publish');
    }

    /** @throws AuthorizationException */
    private function assertManage(User $u): void
    {
        if (!$this->mayManage($u)) {
            throw AuthorizationException::forPermission('cms.manage');
        }
    }

    /** @throws AuthorizationException */
    private function assertPublish(User $u): void
    {
        if (!$this->mayPublish($u)) {
            throw AuthorizationException::forPermission('cms.publish');
        }
    }

    /** @param array<string,mixed> $page @throws AuthorizationException|DomainRuleException */
    private function assertEditable(array $page, User $actor): void
    {
        if ($page['deleted_at'] !== null) {
            throw new DomainRuleException(DomainRuleException::INVALID_TRANSITION, 'Restore this page from the trash before editing it.', [], 422);
        }
        if ($page['status'] === 'archived') {
            throw new DomainRuleException(DomainRuleException::INVALID_TRANSITION, 'Restore this page to a draft before editing it.', [], 422);
        }
        if ($page['status'] === 'published') {
            $this->assertPublish($actor);   // live content changes only with a publisher's permission
        }
    }

    /**
     * @return array<string,mixed>
     * @throws DomainRuleException
     */
    private function load(string $publicId): array
    {
        return $this->pages->find($publicId) ?? throw new DomainRuleException(DomainRuleException::RULE_VIOLATION, 'Page not found.', [], 404);
    }

    /**
     * @param array<string,mixed> $page
     * @param list<string> $from
     * @throws DomainRuleException
     */
    private function move(array $page, array $from, string $to, string $action, User $actor, string $message): void
    {
        if ($page['deleted_at'] !== null) {
            throw new DomainRuleException(DomainRuleException::INVALID_TRANSITION, 'Restore this page from the trash first.', [], 422);
        }
        if (!in_array($page['status'], $from, true)) {
            throw new DomainRuleException(DomainRuleException::INVALID_TRANSITION, $message, [], 422);
        }
        $this->db->transaction(function () use ($page, $to, $action, $actor): void {
            $this->pages->update((int) $page['id'], ['status' => $to, 'updated_by' => $actor->id]);
            $this->audit->log($action, 'cms', 'cms_page', (int) $page['id'], ['status' => $page['status']], ['status' => $to, 'path' => $page['path']], null, $actor);
        });
    }

    /** @param array<string,mixed> $page */
    private function notifyPublishers(array $page, User $actor): void
    {
        $ids = $this->db->select(
            "SELECT DISTINCT u.id FROM users u JOIN roles r ON r.id = u.role_id
             LEFT JOIN role_permissions rp ON rp.role_id = r.id LEFT JOIN permissions p ON p.id = rp.permission_id
             WHERE u.is_active = 1 AND u.deleted_at IS NULL AND u.id <> :me AND (r.name = 'super_admin' OR p.name = 'cms.publish')",
            ['me' => $actor->id],
        );
        foreach ($ids as $row) {
            $this->notifications->notify((int) $row['id'], 'cms_review', 'A page is waiting for review', $actor->name . ' submitted “' . $page['title'] . '” (/' . $page['path'] . ') for review.', null, null, null, 'cms_review:' . $page['id'] . ':' . $page['version'] . ':' . $row['id']);
        }
    }

    // ---- validation -------------------------------------------------------------------------------------------

    /**
     * @param array<string,mixed> $input
     * @param array<string,mixed>|null $existing the page being edited (null when creating)
     * @return array<string,mixed> every column an editor can set, normalised
     * @throws ValidationException
     */
    private function validated(array $input, ?array $existing, User $actor): array
    {
        $errors = [];
        $str = static fn (string $k): string => trim((string) ($input[$k] ?? ''));

        $title = $str('title');
        if ($title === '' || mb_strlen($title) > 180) {
            $errors['title'] = ['Give the page a title of up to 180 characters.'];
        }
        $body = trim(str_replace(["\r\n", "\r"], "\n", (string) ($input['body'] ?? '')));
        if ($body === '') {
            $errors['body'] = ['Write something on the page.'];
        } elseif (mb_strlen($body) > 100000) {
            $errors['body'] = ['The page is too long (100,000 characters at most).'];
        } elseif (preg_match('/[\x00-\x08\x0B\x0C\x0E-\x1F]/', $body) === 1) {
            $errors['body'] = ['The page contains characters that are not allowed.'];
        }

        $path = $this->validPath($str('path'), $title, $existing, $errors);

        $summary = $str('summary');
        if (mb_strlen($summary) > 300 || str_contains($summary, "\n")) {
            $errors['summary'] = ['The summary must be one line of at most 300 characters.'];
        }
        $template = $str('template') === '' ? 'default' : $str('template');
        if (!isset(self::TEMPLATES[$template])) {
            $errors['template'] = ['Choose one of the layouts.'];
        }
        foreach (['meta_title' => 120, 'og_title' => 120, 'focus_keyword' => 80, 'featured_alt' => 160] as $k => $max) {
            if (mb_strlen($str($k)) > $max || preg_match('/[\x00-\x1F\x7F]/', $str($k)) === 1) {
                $errors[$k] = ["Use up to {$max} characters on a single line."];
            }
        }
        foreach (['meta_description' => 200, 'og_description' => 200] as $k => $max) {
            if (mb_strlen($str($k)) > $max || preg_match('/[\x00-\x1F\x7F]/', $str($k)) === 1) {
                $errors[$k] = ["Use up to {$max} characters on a single line."];
            }
        }
        $canonical = $str('canonical_url');
        if ($canonical !== '' && preg_match('#^https://[^\s<>"\']{4,290}$#D', $canonical) !== 1) {
            $errors['canonical_url'] = ['The canonical address must be a full https:// address.'];
        }
        $image = $str('featured_image');
        if ($image !== '' && preg_match('#^(?:https://[^\s<>"\']{4,290}|/(?!/)[^\s<>"\']{1,290})$#D', $image) !== 1) {
            $errors['featured_image'] = ['Use a https:// address or a site path such as /media/photo.jpg.'];
        }
        $robots = $str('robots') === '' ? 'index' : $str('robots');
        if (!in_array($robots, ['index', 'noindex'], true)) {
            $errors['robots'] = ['Choose index or noindex.'];
        }
        $priority = $str('sitemap_priority') === '' ? '0.5' : $str('sitemap_priority');
        if (preg_match('/^(?:0\.[1-9]|1\.0|1)$/D', $priority) !== 1) {
            $errors['sitemap_priority'] = ['Priority is a number from 0.1 to 1.0.'];
        }
        $priority = number_format((float) $priority, 1, '.', '');
        $freq = $str('sitemap_changefreq') === '' ? 'monthly' : $str('sitemap_changefreq');
        if (!in_array($freq, self::CHANGEFREQ, true)) {
            $errors['sitemap_changefreq'] = ['Choose how often the page changes.'];
        }

        $faq = $this->validFaq($input, $errors);

        $publishAt = $existing['publish_at'] ?? null;
        $unpublishAt = $existing['unpublish_at'] ?? null;
        if ($this->mayPublish($actor)) {
            [$publishAt, $unpublishAt] = $this->validWindow($str('publish_at'), $str('unpublish_at'), $errors);
        }

        if ($errors !== []) {
            throw new ValidationException($errors);
        }
        $html = CmsFormatter::toHtml($body);

        return [
            'title' => $title, 'path' => $path, 'summary' => $summary === '' ? null : $summary, 'body_source' => $body, 'body_html' => $html,
            'word_count' => CmsFormatter::wordCount($html), 'template' => $template,
            'meta_title' => $str('meta_title') ?: null, 'meta_description' => $str('meta_description') ?: null, 'focus_keyword' => $str('focus_keyword') ?: null,
            'canonical_url' => $canonical ?: null, 'robots' => $robots, 'og_title' => $str('og_title') ?: null, 'og_description' => $str('og_description') ?: null,
            'featured_image' => $image ?: null, 'featured_alt' => $str('featured_alt') ?: null,
            'in_sitemap' => !empty($input['in_sitemap']) ? 1 : 0, 'sitemap_priority' => $priority, 'sitemap_changefreq' => $freq,
            'faq' => $faq === [] ? null : (string) json_encode($faq, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
            'publish_at' => $publishAt, 'unpublish_at' => $unpublishAt,
        ];
    }

    /**
     * @param array<string,mixed>|null $existing
     * @param array<string,list<string>> $errors
     */
    private function validPath(string $raw, string $title, ?array $existing, array &$errors): string
    {
        if ($existing !== null && $existing['published_at'] !== null) {
            $wanted = $this->normalizePath($raw);
            if ($wanted !== '' && $wanted !== $existing['path']) {
                $errors['path'] = ['The address is frozen once a page has been published — search engines and visitors already know it.'];
            }

            return (string) $existing['path'];
        }
        $path = $this->normalizePath($raw);
        if ($path === '') {
            $base = Slug::make($title, 100);
            $path = $base === 'job' ? 'page-' . strtolower(substr(Ulid::generate(), -6)) : $base;
        }
        $segments = explode('/', $path);
        if (count($segments) > 3 || strlen($path) > 150) {
            $errors['path'] = ['The address can have up to three parts (a/b/c) and 150 characters.'];
        } else {
            foreach ($segments as $s) {
                if (preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*$/D', $s) !== 1) {
                    $errors['path'] = ['Each part of the address may use lowercase letters, numbers and single hyphens only.'];
                    break;
                }
            }
        }
        if (!isset($errors['path']) && $this->reserved->isReserved($segments[0])) {
            $errors['path'] = ['“' . $segments[0] . '” is used by the system — choose another address.'];
        }
        if (!isset($errors['path']) && $this->pages->pathExists($path, (int) ($existing['id'] ?? 0))) {
            $errors['path'] = ['Another page already uses this address.'];
        }

        return $path;
    }

    private function normalizePath(string $raw): string
    {
        $p = strtolower(trim($raw));
        $p = (string) preg_replace('#/{2,}#', '/', $p);

        return trim($p, '/ ');
    }

    /** A free address starting from $base ("x-copy", "x-copy-2"…). */
    private function freePath(string $base): string
    {
        $base = substr($base, 0, 140);
        $path = $base;
        for ($n = 2; $this->pages->pathExists($path); $n++) {
            $path = $base . '-' . $n;
        }

        return $path;
    }

    /**
     * @param array<string,mixed> $input
     * @param array<string,list<string>> $errors
     * @return list<array{q:string,a:string}>
     */
    private function validFaq(array $input, array &$errors): array
    {
        $qs = is_array($input['faq_q'] ?? null) ? array_values($input['faq_q']) : [];
        $as = is_array($input['faq_a'] ?? null) ? array_values($input['faq_a']) : [];
        $out = [];
        foreach ($qs as $i => $q) {
            $q = trim((string) $q);
            $a = trim(str_replace("\r\n", "\n", (string) ($as[$i] ?? '')));
            if ($q === '' && $a === '') {
                continue;
            }
            if ($q === '' || $a === '' || mb_strlen($q) > 200 || mb_strlen($a) > 2000 || str_contains($q, "\n") || preg_match('/[\x00-\x08\x0B\x0C\x0E-\x1F]/', $q . $a) === 1) {
                $errors['faq'] = ['Each FAQ needs a one-line question (200 characters at most) and an answer (2,000 at most).'];
                break;
            }
            $out[] = ['q' => $q, 'a' => $a];
        }
        if (count($out) > self::MAX_FAQ) {
            $errors['faq'] = ['At most ' . self::MAX_FAQ . ' questions.'];
        }

        return $out;
    }

    /**
     * @param array<string,list<string>> $errors
     * @return array{0:?string,1:?string} [go-live, take-down] as UTC 'Y-m-d H:i:s'
     */
    private function validWindow(string $publishAt, string $unpublishAt, array &$errors): array
    {
        $from = $publishAt === '' ? null : $this->parseLocal($publishAt);
        $to = $unpublishAt === '' ? null : $this->parseLocal($unpublishAt);
        if ($publishAt !== '' && $from === null) {
            $errors['publish_at'] = ['Enter the go-live time as a date and time.'];
        }
        if ($unpublishAt !== '' && $to === null) {
            $errors['unpublish_at'] = ['Enter the take-down time as a date and time.'];
        }
        if ($from !== null && $to !== null && strtotime($to . ' UTC') <= strtotime($from . ' UTC')) {
            $errors['unpublish_at'] = ['The take-down time must be after the go-live time.'];
        }

        return [$from, $to];
    }

    /** A local `Y-m-d\TH:i` (or `Y-m-d H:i`) in the business time zone → UTC 'Y-m-d H:i:s', or null when it is not a real date. */
    public function parseLocal(string $local): ?string
    {
        $tz = new \DateTimeZone((string) $this->app->config()->get('app.timezone', 'UTC'));
        foreach (['!Y-m-d\TH:i', '!Y-m-d H:i', '!Y-m-d\TH:i:s'] as $format) {
            $d = \DateTimeImmutable::createFromFormat($format, $local, $tz);
            if ($d !== false && $d->format(substr($format, 1)) === $local) {
                return $d->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s');
            }
        }

        return null;
    }

    // ---- rows -------------------------------------------------------------------------------------------------

    /** @param array<string,mixed> $data @return array<string,mixed> the columns written on create/update */
    private function row(array $data): array
    {
        $row = [];
        foreach (['title', 'body_source', 'body_html', 'word_count', ...self::SNAPSHOT] as $c) {
            $row[$c] = $data[$c];
        }

        return $row;
    }

    /** @param array<string,mixed> $data @return array<string,mixed> */
    private function snapshot(array $data): array
    {
        $snap = [];
        foreach (self::SNAPSHOT as $c) {
            $snap[$c] = $data[$c] ?? null;
        }

        return $snap;
    }

    /** @param array<string,mixed> $row @return array<string,mixed> */
    private function snapshotFromRow(array $row): array
    {
        return $this->snapshot($row);
    }
}
