<?php
/** @var array<string,mixed> $post */

use App\Support\BlogFormatter;
use App\Support\PublicFormat;

$org = (string) setting('business.name', config('app.name'));
$site = rtrim((string) config('app.url', ''), '/');
$summary = $post['excerpt'] ?: BlogFormatter::plainText((string) $post['body_html'], 160);
$this->layout('layouts.public', [
    'title' => $post['title'],
    'description' => mb_substr($summary, 0, 160),
    'canonical' => 'blog/' . $post['slug'],
]);
$this->start('head');
?>
    <script type="application/ld+json"><?= PublicFormat::json(PublicFormat::articleLd($post, $org, $site . '/blog/' . $post['slug'], $summary)) ?></script>
<?php
$this->stop();
$this->start('content');
?>
<article class="mx-auto max-w-2xl px-4 py-12">
    <p class="text-sm"><a href="/blog" class="text-brand-600">← All articles</a></p>
    <h1 class="mt-2 text-3xl font-bold text-slate-900"><?= e($post['title']) ?></h1>
    <p class="mt-2 text-sm text-slate-500">
        <time datetime="<?= e_attr(substr((string) $post['published_at'], 0, 10)) ?>"><?= e(date('j F Y', strtotime((string) $post['published_at'] . ' UTC'))) ?></time>
        <?php if (!empty($post['author_name'])): ?> · <?= e($post['author_name']) ?><?php endif ?>
    </p>

    <div class="mt-6 space-y-4 leading-relaxed text-slate-800 [&_a]:text-brand-600 [&_a]:font-medium [&_h3]:mt-6 [&_h3]:text-xl [&_h3]:font-semibold [&_h4]:mt-4 [&_h4]:text-lg [&_h4]:font-semibold [&_ol]:list-decimal [&_ol]:pl-6 [&_ul]:list-disc [&_ul]:pl-6">
        <?= $post['body_html'] /* generated by BlogFormatter: escaped text plus an allowlist of tags */ ?>
    </div>

    <aside class="mt-10 card card-body">
        <p class="font-medium text-slate-900">Looking to work or travel abroad?</p>
        <p class="mt-1 text-sm text-slate-600">See what is open right now, or talk to our team.</p>
        <p class="mt-3 flex flex-wrap gap-2"><a class="btn btn-primary btn-sm" href="/overseas-jobs">Browse jobs</a><a class="btn btn-secondary btn-sm" href="/travel-packages">Travel packages</a><a class="btn btn-ghost btn-sm" href="/contact">Contact us</a></p>
    </aside>
</article>
<?php $this->stop(); ?>
