<?php
/**
 * Printable receipt. It renders the snapshot frozen when the money was received; only the
 * "reversed" banner reflects the payment's live status.
 * @var \App\Models\Payment $payment @var array{receipt_number:string,issued_at:string,snapshot:array<string,mixed>} $receipt
 */
$s = $receipt['snapshot'];
$cur = (string) ($s['currency'] ?? $payment->currency);
$money = static fn (mixed $v): string => e($cur . ' ' . number_format((float) $v, 2));
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow, noarchive">
    <title>Receipt <?= e($receipt['receipt_number']) ?></title>
    <style>
        body { font-family: system-ui, -apple-system, "Segoe UI", sans-serif; color: #0f172a; margin: 0; background: #f1f5f9; }
        .sheet { max-width: 640px; margin: 24px auto; background: #fff; padding: 32px; border: 1px solid #e2e8f0; border-radius: 8px; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        .muted { color: #64748b; font-size: 13px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 14px; }
        th, td { text-align: left; padding: 8px 0; border-bottom: 1px solid #e2e8f0; }
        td.r, th.r { text-align: right; }
        .total { font-size: 18px; font-weight: 600; }
        .void { background: #fee2e2; color: #991b1b; padding: 8px 12px; border-radius: 6px; margin-bottom: 16px; font-weight: 600; }
        .bar { max-width: 640px; margin: 16px auto 0; text-align: right; }
        button { font: inherit; padding: 6px 14px; }
        @media print { body { background: #fff; } .sheet { border: 0; margin: 0; padding: 0; } .bar { display: none; } }
    </style>
</head>
<body>
<div class="bar"><button type="button" onclick="window.print()">Print</button></div>
<div class="sheet">
    <?php if (!$payment->isRecorded()): ?><div class="void">REVERSED — this payment was reversed: <?= e((string) $payment->reversedReason) ?></div><?php endif ?>
    <h1>Payment receipt</h1>
    <p class="muted"><?= e((string) ($s['branch'] ?? '')) ?></p>

    <table>
        <tr><th>Receipt no.</th><td class="r"><?= e($receipt['receipt_number']) ?></td></tr>
        <tr><th>Payment no.</th><td class="r"><?= e((string) ($s['payment_number'] ?? '')) ?></td></tr>
        <tr><th>Received from</th><td class="r"><?= e((string) ($s['customer']['name'] ?? '')) ?><?= !empty($s['customer']['phone']) ? '<br><span class="muted">' . e((string) $s['customer']['phone']) . '</span>' : '' ?></td></tr>
        <tr><th>Date</th><td class="r"><?= e(substr((string) ($s['paid_at'] ?? ''), 0, 16)) ?></td></tr>
        <tr><th>Method</th><td class="r"><?= e((string) ($s['method'] ?? '')) ?><?= !empty($s['reference']) ? ' · ' . e((string) $s['reference']) : '' ?></td></tr>
    </table>

    <?php if (!empty($s['allocations'])): ?>
        <table>
            <thead><tr><th>Applied to invoice</th><th class="r">Amount</th></tr></thead>
            <tbody>
            <?php foreach ((array) $s['allocations'] as $a): ?>
                <tr><td><?= e((string) $a['invoice_number']) ?></td><td class="r"><?= $money($a['amount']) ?></td></tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php endif ?>

    <table><tr><td class="total">Amount received</td><td class="r total"><?= $money($s['amount'] ?? 0) ?></td></tr></table>
    <p class="muted" style="margin-top:24px">Received by <?= e((string) ($s['received_by'] ?? '')) ?> · issued <?= e(substr($receipt['issued_at'], 0, 16)) ?> UTC. This receipt was generated by the system and is valid without a signature.</p>
</div>
</body>
</html>
