<?php
/**
 * A website page (Admin → Pages). @var array<string,mixed> $page @var \App\Cms\CmsRenderer $renderer @var bool $preview
 * The body is HTML generated by CmsFormatter (escaped text + allowlisted markup) with placeholders filled by CmsRenderer.
 */

use App\Cms\CmsFormatter;
use App\Support\PublicFormat;

$site = rtrim((string) config('app.url', ''), '/');
$org = (string) setting('business.name', config('app.name'));
$faq = json_decode((string) ($page['faq'] ?? ''), true);
$faq = is_array($faq) ? array_values(array_filter($faq, static fn ($f): bool => is_array($f) && isset($f['q'], $f['a']))) : [];
$summary = (string) ($page['meta_description'] ?: ($page['summary'] ?: CmsFormatter::plainText((string) $page['body_html'], 160)));
$url = $site . '/' . $page['path'];
$noindex = $preview || $page['robots'] === 'noindex';
$width = $page['template'] === 'wide' ? 'max-w-6xl' : 'max-w-3xl';
$faqInBody = str_contains((string) $page['body_html'], 'data-sc="faq"');

$this->layout('layouts.public', [
    'title' => (string) ($page['meta_title'] ?: $page['title']),
    'description' => mb_substr($summary, 0, 200),
    'canonical' => ($page['canonical_url'] ?? '') !== '' ? (string) $page['canonical_url'] : $page['path'],
    'robots' => $preview ? 'noindex,nofollow' : ($noindex ? 'noindex,follow' : null),
    'ogImage' => (string) ($page['featured_image'] ?? ''),
    'ogTitle' => (string) ($page['og_title'] ?: ($page['meta_title'] ?: $page['title'])),
    'ogDescription' => (string) ($page['og_description'] ?: $summary),
    'chrome' => $page['template'] !== 'landing',
]);

$crumbs = [['@type' => 'ListItem', 'position' => 1, 'name' => 'Home', 'item' => $site . '/']];
$acc = '';
foreach (explode('/', (string) $page['path']) as $i => $seg) {
    $acc .= ($acc === '' ? '' : '/') . $seg;
    $isLast = $acc === $page['path'];
    $crumbs[] = ['@type' => 'ListItem', 'position' => $i + 2, 'name' => $isLast ? (string) $page['title'] : ucwords(str_replace('-', ' ', $seg))] + ($isLast ? [] : ['item' => $site . '/' . $acc]);
}
$graph = [
    ['@type' => 'WebPage', '@id' => $url, 'url' => $url, 'name' => (string) $page['title'], 'description' => $summary, 'inLanguage' => 'en',
        'dateModified' => gmdate('c', strtotime((string) $page['updated_at'] . ' UTC'))]
        + ($page['published_at'] ? ['datePublished' => gmdate('c', strtotime((string) $page['published_at'] . ' UTC'))] : []),
    ['@type' => 'BreadcrumbList', 'itemListElement' => $crumbs],
];
if ($faq !== []) {
    $graph[] = ['@type' => 'FAQPage', 'mainEntity' => array_map(static fn (array $f): array => ['@type' => 'Question', 'name' => (string) $f['q'], 'acceptedAnswer' => ['@type' => 'Answer', 'text' => (string) $f['a']]], $faq)];
}

$this->start('head');
?>
    <?php if (!$preview): ?><script type="application/ld+json"><?= PublicFormat::json(['@context' => 'https://schema.org', '@graph' => $graph]) ?></script><?php endif ?>
<?php
$this->stop();
$this->start('content');
?>
<?php if ($preview): ?>
    <div class="bg-amber-100 px-4 py-2 text-center text-sm font-medium text-amber-900" role="status">Preview — this is not public. Search engines are told to ignore it.</div>
<?php endif ?>
<article class="mx-auto <?= $width ?> px-4 py-12">
    <h1 class="text-3xl font-bold text-slate-900"><?= e((string) $page['title']) ?></h1>
    <?php if (!empty($page['summary'])): ?><p class="mt-3 text-lg text-slate-600"><?= e((string) $page['summary']) ?></p><?php endif ?>
    <?php if (!empty($page['featured_image'])): ?>
        <figure class="mt-6"><img class="h-auto w-full rounded-lg" src="<?= e_attr((string) $page['featured_image']) ?>" alt="<?= e_attr((string) ($page['featured_alt'] ?? '')) ?>" decoding="async"></figure>
    <?php endif ?>

    <div class="cms-prose mt-6">
        <?= $renderer->render((string) $page['body_html'], $faq) /* generated by CmsFormatter; placeholders filled and escaped by CmsRenderer */ ?>
        <?php if ($faq !== [] && !$faqInBody): ?><?= \App\Cms\CmsRenderer::faq($faq) /* escaped inside */ ?><?php endif ?>
    </div>

    <p class="mt-10 text-xs text-slate-500">Last updated <time datetime="<?= e_attr(substr((string) $page['updated_at'], 0, 10)) ?>"><?= e(date('j F Y', strtotime((string) $page['updated_at'] . ' UTC'))) ?></time></p>
</article>
<?php $this->stop(); ?>
